services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manup-api
    restart: always
    ports:
      - "7780:7780"
    environment:
      DB_TYPE: PGLITE
      DB_DIR: /app/manup
      MASTER_KEY: "9a8b7c6d5e4f3g2h1i0j9k8l7m6n5o4p"
      JWT_SECRET: "super_secret_jwt_sign_key_manup_2026"
      PORT: 7780
    volumes:
      - pglite_data:/app/manup

volumes:
  pglite_data:
